version: '3.9'

services:
  mongodb:
    image: mongo:4.4.6-bionic
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: server
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - app-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3000:3000'
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
